// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrqtrurckqhiagaentvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycXRydXJja3FoaWFnYWVudHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTI2MDEsImV4cCI6MjA1NzgyODYwMX0.XhHnNagmRyNu1j5c8aEo3q_B6qO9_Bek0W5Zec6Avh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);